- hosts: jenkins
  become: yes
  tasks:
    - name: Install Java
      yum:
        name: java-17-openjdk
        state: present

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install Jenkins repo
      yum_repository:
        name: jenkins
        description: Jenkins repo
        baseurl: http://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
        enabled: true
